sudo: false
language: node_js
node_js:
  - '10'
  - '12'
# keep the npm cache to speed up installs
cache:
  directories:
    - '$HOME/.npm'
after_success:
  - npm run cov:send
deploy:
  - provider: script
    script: .github/deploy_prepare.sh
    skip_cleanup: true
    on: &on
      branch: master
  - provider: script
    script: npm run release:ci
    skip_cleanup: true
    on: *on
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_AUTH_TOKEN
  - provider: releases
    api_key: $GITHUB_TOKEN
    name: Release $TRAVIS_TAG
    body: See [CHANGELOG.md](https://github.com/$TRAVIS_REPO_SLUG/blob/master/CHANGELOG.md)
    on: *on
